import SwiftUI
//swiftlint:disable type_body_length

enum WLTexts: String {
    
    // MARK: - Common
    case commonTextWelcome                                                      = "Common.Text.Welcome"
    case commonSetTitleContinue                                                 = "Common.SetTitle.Continue"
    case commonTextRegister                                                     = "Common.Text.Register"
    case commonTextOK                                                           = "Common.Text.OK"
    case commonTextDone                                                         = "Common.Text.Done"
    case commonTextError                                                        = "Common.Text.Error"
    case commonTextConnectionError                                              = "Common.Text.ConnectionError"
    case commonTextTime                                                         = "Common.Text.Time"
    case commonSetTitleUpdate                                                   = "Common.SetTitle.Update"
    case commonTextPassword                                                     = "Common.Text.Password"
    case commonTextPasswordAgain                                                = "Common.Text.PasswordAgain"
    case commonTextErrorException                                               = "Common.Text.Error.Exception"
    case commonTextLogin                                                        = "Common.Text.Login"
    case commonTextInfo                                                         = "Common.Text.Info"
    case commonTextEMail                                                        = "Common.Text.EMail"
    case commonTextApply                                                        = "Common.Text.Apply"
    case commonTextCopied                                                       = "Common.Text.Copied"
    case commonTextAccept                                                       = "Common.Text.Accept"
    case commonTextVerify                                                       = "Common.Text.Verify"
    case commonTextCancel                                                       = "Common.Text.Cancel"
    case commonTextTryAgain                                                     = "Common.Text.TryAgain"
    case commonTextDeny                                                         = "Common.Text.Deny"
    case commonTextOther                                                        = "Common.Text.Other"
    case commonTextExplanation                                                  = "Common.Text.Explanation"
    case commonTitleTransactionDetail                                           = "Common.Title.TransactionDetail"
    case commonTitleTransactionSummary                                          = "Common.Title.TransactionSummary"
    case commonTitleProcessingFee                                               = "Common.Title.ProcessingFee"
    case commonTextTotalAmount                                                  = "Common.Text.TotalAmount"
    case commonTextSendNow                                                      = "Common.Text.SendNow"
    case commonTextAskNow                                                       = "Common.Text.AskNow"
    case commonTextAmount                                                       = "Common.Text.Amount"
    case commonTextEmptyTextField                                               = "Common.Text.EmptyTextField"
    case commonTextYes                                                          = "Common.Text.Yes"
    case commonTextNo                                                           = "Common.Text.No"
    case commonTextStart                                                        = "Common.Text.Start"
    case commonTextSuccess                                                      = "Common.Text.Success"
    case commonTextEnterAmount                                                  = "Common.Text.EnterAmount"
    case commonTextShare                                                        = "Common.Text.Share"
    case commonTextName                                                         = "Common.Text.Name"
    case commonTextSurName                                                      = "Common.Text.SurName"
    case commonTextNameSurname                                                  = "Common.Text.NameSurname"
    case commonTextBalance                                                      = "Common.Text.Balance"
    case commonTextIBAN                                                         = "Common.Text.IBAN"
    case commonTextForUse                                                       = "Common.Text.ForUse"
    case commonTextOpen                                                         = "Common.Text.Open"
    case commonTextDelete                                                       = "Common.Text.Delete"
    case commonTextRequestSuccessFull                                           = "Common.Text.RequestSuccessFull"
    // MARK: - Begin
    case commonTextCVV                                                          = "Common.Text.CVV"
    case commonTextBalanceAtTheBeginningOfThePeriod                             = "Common.Text.BalanceAtTheBeginningOfThePeriod"
    case commonTextBalanceAtTheEndOfThePeriod                                   = "Common.Text.BalanceAtTheEndOfThePeriod"
    case commonTextReceipt                                                      = "Common.Text.Receipt"
    case commonTextChangePhoneNumber                                            = "Common.Text.ChangePhoneNumber"
    case commonTextWithdrawMoney                                                = "Common.Text.WithdrawMoney"
    case commonTextCurrentBalance                                               = "Common.Text.CurrentBalance"
    case commonTextYouEnteredYourInformationIncorrectly                         = "Common.Text.YouEnteredYourInformationIncorrectly"
    case commonTextShopNow                                                      = "Common.Text.ShopNow"
    case commonTextSplit                                                        = "Common.Text.Split"
    case commonTextSplitTheSpending                                             = "Common.Text.SplitTheSpending"
    case commonTextSPLITTHESPENDING                                             = "Common.Text.SPENDSPLIT"
    case commonTextWLBLW                                                        = "Common.Text.WLBLW"
    case commonTextDetail                                                       = "Common.Text.Detail"
    case commonTextErrorCreatingPdf                                             = "Common.Text.ErrorCreatingPdf"
    case commonTextSuccessful                                                   = "Common.Text.Successful"
    case commonTextYourTransactionIsSuccessful                                  = "Common.Text.YourTransactionIsSuccessful"
    case commonTextUnknownErrorOccurred                                         = "Common.Text.UnknownErrorOccurred"
    case commonTextCardCreated                                                  = "Common.Text.CardCreated"
    case commonTextMyself                                                       = "Common.Text.Myself"
    
    case beginScreenTextPhoneNumber                                             = "BeginScreen.Text.PhoneNumber"
    // MARK: - Information
    case ınfoTextVireTextInformationText                                        = "InfoTextVire.Text.InformationText"
    case ınfoTextViewTextTitle                                                  = "InfoTextView.Text.Title"
    // MARK: - Register
    case registerViewTextUserAgreement                                          = "RegisterView.Text.UserAgreement"
    case registerViewTextZubizuAdvertisement                                    = "RegisterView.Text.Zubizu.Advertisement"
    case registerViewTextDgParaAdvertisement                                    = "RegisterView.Text.DgPara.Advertisement"
    case registerViewTextDgParaAdvertisementMessages                            = "RegisterView.Text.DgPara.Advertisement.Messages"
    case registerViewTextRegister                                               = "RegisterView.Text.Register"
    case registerViewTextName                                                   = "RegisterView.Text.Name"
    case registerViewTextReferenceCode                                          = "RegisterView.Text.ReferenceCode"
    case registerViewTextSurName                                                = "RegisterView.Text.SurName"
    case registerViewTextIDNumber                                               = "RegisterView.Text.IDNumber"
    case registerViewTextBirthDate                                              = "RegisterView.Text.BirthDate"
    case registerViewTextValidationEmail                                        = "RegisterView.Text.Validation.Email"
    case registerViewSecondTextPassword                                         = "RegisterViewSecond.Text.Password"
    case registerViewSecondTextPasswordAgain                                    = "RegisterViewSecond.Text.PasswordAgain"
    case registerViewSecondTextForCorrectPassword                               = "RegisterViewSecond.Text.ForCorrectPassword"
    case registerViewSecondTextFirstRule                                        = "RegisterViewSecond.Text.FirstRule"
    case registerViewSecondTextSecondRule                                       = "RegisterViewSecond.Text.SecondRule"
    case registerViewSecondTextThirdRuler                                       = "RegisterViewSecond.Text.ThirdRuler"
    case registerViewSecondTextFourthRule                                       = "RegisterViewSecond.Text.FourthRule"
    case registerViewSecondTextFifthRule                                        = "RegisterViewSecond.Text.FifthRule"
    // MARK: - OTP
    case otpScreenTextVerificationCode                                          = "OtpScreen.Text.VerificationCode"
    case otpScreenTextPlease                                                    = "OtpScreen.Text.Please"
    case otpScreenTextReSend                                                    = "OtpScreen.Text.ReSend"
    case otpScreenTextToYourNumber                                              = "OtpScreen.Text.ToYourNumber"
    // MARK: - Reset Password With Old Pin
    case resetPasswordWithOldPinTextResetPassword                               = "ResetPasswordWithOldPin.Text.ResetPassword"
    case resetPasswordWithOldPinTextOldPassword                                 = "ResetPasswordWithOldPin.Text.OldPassword"
    case resetPasswordWithOldPinTextNewPassword                                 = "ResetPasswordWithOldPin.Text.NewPassword"
    case resetPasswordWithOldPinTextNewPasswordAgain                            = "ResetPasswordWithOldPin.Text.NewPasswordAgain"
    case resetPasswordWithOldPinTextResetForYourSecurity                        = "ResetPasswordWithOldPin.Text.ResetForYourSecurity"
    case resetPasswordWithOldPinTextPasswordsDontMatch                          = "ResetPasswordWithOldPin.Text.PasswordsDontMatch"
    case resetPasswordWithOldPinTextPasswordException                           = "ResetPasswordWithOldPin.Text.PasswordException"
    // MARK: - Security Question
    case securityQuestionTextCharackter                                         = "SecurityQuestion.Text.Charackter"
    case securityQuestionTextSpacer                                             = "SecurityQuestion.Text.Spacer"
    case securityQuestionTextSpecialCharackter                                  = "SecurityQuestion.Text.SpecialCharackter"
    case securityQuestionTextSecurityQuestion                                   = "SecurityQuestion.Text.SecurityQuestion"
    case securityQuestionTextSetSecurityQuestion                                = "SecurityQuestion.Text.SetSecurityQuestion"
    case securityQuestionTextAnswerQuestion                                     = "SecurityQuestion.Text.AnswerQuestion"
    case securityQuestionTextSecurityQuestionExplanation                        = "SecurityQuestion.Text.SecurityQuestionExplanation"
    case securityQuestionTextAnswerSecurityQuestion                             = "SecurityQuestion.Text.AnswerSecurityQuestion"
    // MARK: - Verify Account
    case verifyAccountInfoTextGoodNews                                          = "VerifyAccountInfo.Text.GoodNews"
    case verifyAccountInfoTextSuccesfullyMembership                             = "VerifyAccountInfo.Text.SuccesfullyMembership"
    case verifyAccountInfoTextOffers                                            = "VerifyAccountInfo.Text.Offers"
    case verifyAccountInfoTextUseOffers                                         = "VerifyAccountInfo.Text.UseOffers"
    case verifyAccountInfoTextManageWallet                                      = "VerifyAccountInfo.Text.ManageWallet"
    case verifyAccountInfoTextMakeInstallment                                   = "VerifyAccountInfo.Text.MakeInstallment"
    case verifyAccountInfoTextEarnCash                                          = "VerifyAccountInfo.Text.EarnCash"
    case verifyAccountInfoTextYourWallet                                        = "VerifyAccountInfo.Text.YourWallet"
    case verifyAccountInfoTextWithMoreLimits                                    = "VerifyAccountInfo.Text.WithMoreLimits"
    case verifyAccountInfoTextToUse                                             = "VerifyAccountInfo.Text.ToUse"
    case verifyAccountInfoTitleVerifyID                                         = "VerifyAccountInfo.Title.VerifyID"
    // MARK: - User Agreement
    case userAgreementTitleNaivigationTitle                                     = "UserAgreement.Title.NaivigationTitle"
    case loginWithPasswordViewTextForgotPassword                                = "LoginWithPasswordView.Text.ForgotPassword"
    case loginWithPasswordViewTextForgotPasswordUpperCase                                = "LoginWithPasswordView.Text.ForgotPassword.UpperCase"
    case loginWithPasswordViewTextErrorBlockAccount                             = "LoginWithPasswordView.Text.Error.BlockAccount"
    case loginWithPasswordViewTextErrorResetPassword                            = "LoginWithPasswordView.Text.Error.ResetPassword"
    case loginWithPasswordViewTextErrorResetMyPassword                          = "LoginWithPasswordView.Text.Error.ResetMyPassword"
    case forgotPasswordEmailTextResetPassword                                   = "ForgotPasswordEmail.Text.ResetPassword"
    case forgotPasswordEmailTextPlsEnterEmail                                   = "ForgotPasswordEmail.Text.PlsEnterEmail"
    case forgotPasswordEmailTextVerificationLink                                = "ForgotPasswordEmail.Text.VerificationLink"
    case forgotPasswordEmailTextIfNotAccessMail                                 = "ForgotPasswordEmail.Text.IfNotAccessMail"
    case forgotPasswordEmailTextSendLink                                        = "ForgotPasswordEmail.Text.SendLink"
    case forgotPasswordEmailTextForgotPassword                                  = "ForgotPasswordEmail.Text.ForgotPassword"
    case homeScreenTextMyWallet                                                 = "HomeScreen.Text.MyWallet"
    case homeScreenTextWalletID                                                 = "HomeScreen.Text.WalletID"
    case homeScreenTextIncreaseLimit                                            = "HomeScreen.Text.IncreaseLimit"
    case homeScreenTextMyZBZCards                                               = "HomeScreen.Text.MyZBZCards"
    case homeScreenTextAll                                                      = "HomeScreen.Text.All"
    case homeScreenTextMoney = "HomeScreen.Text.Money"
    case homeScreenTextAsk = "HomeScreen.Text.Ask"
    case homeScreenTextLoad = "HomeScreen.Text.Load"
    case homeScreenTextSend = "HomeScreen.Text.Send"
    case homeScreenTextQr = "HomeScreen.Text.Qr"
    case homeScreenTextPayment = "HomeScreen.Text.Payment"
    case microCreditNotLoginTextUseMikroCredit                                  = "MicroCreditNotLogin.Text.UseMikroCredit"
    case waitingTransactionsEmptyTextWaitingTransactionsNotHave                 = "WaitingTransactionsEmpty.Text.WaitingTransactionsNotHave"
    case waitingTransactionsTextAlertText                                       = "WaitingTransactions.Text.AlertText"
    case waitingTransactionsTitleAlertTitle                                     = "WaitingTransactions.Title.AlertTitle"
    case transactionHistoryNotLoginTextPleaseLogin                              = "TransactionHistoryNotLogin.Text.PleaseLogin"
    case microCreditToApplyTextClickForMicroCredit                              = "MicroCreditToApply.Text.ClickForMicroCredit"
    case emptyTransactionTextDontHaveTransaction                                = "EmptyTransaction.Text.DontHaveTransaction"
    case customListViewTitleRepeat                                              = "CustomListView.Title.Repeat"
    case customListViewTextAll                                                  = "CustomListView.Text.All"
    case signInPopUpForgotPasswordPopUpTextPleaseLoginWithBirthday              = "SignInPopUp_ForgotPasswordPopUp.Text.PleaseLoginWithBirthday"
    case signInPopUpForgotPasswordPopUpTextSaveEmail                            = "SignInPopUp_ForgotPasswordPopUp.Text.SaveEmail"
    case signInPopUpForgotPasswordPopUpTextLinkSent                             = "SignInPopUp_ForgotPasswordPopUp.Text.LinkSent"
    case signInPopUpForgotPasswordPopUpTextLinkSending                          = "SignInPopUp_ForgotPasswordPopUp.Text.LinkSending"
    
    case signInPopUpForgotPasswordPopUpTextSetPassword                         = "SignInPopUp_ForgotPasswordPopUp.Text.SetPassword"
    case signInPopUpTextImportantOnNewZubizu                                    = "SignInPopUp.Text.ImportantOnNewZubizu"
    case forgotPasswordPopUpTextPasswordReset                                   = "ForgotPasswordPopUp.Text.PasswordReset"
    case forgotPasswordPopUpTextPasswordResetLink                               = "ForgotPasswordPopUp.Text.PasswordResetLink"
    case resetPasswordSuccessPopUpTextPasswordSuccess                           = "ResetPasswordSuccessPopUp.Text.PasswordSuccess"
    case resetPasswordSuccessPopUpTextZubizuPrivilege                           = "ResetPasswordSuccessPopUp.Text.ZubizuPrivilege"
    case resetPasswordSuccessPopUpTextDiscover                                  = "ResetPasswordSuccessPopUp.Text.Discover"
    case customToggleTextRememberMe                                             = "CustomToggle.Text.RememberMe"
    case loginScreenTextFieldTextPhoneNumber                                    = "LoginScreenTextField.Text.PhoneNumber"
    case transactionActionSheetTitleLoadMoney                                   = "TransactionActionSheet.Title.LoadMoney"
    case transactionActionSheetTitlePayBill                                     = "TransactionActionSheet.Title.PayBill"
    case transactionActionSheetTitleSendMoney                                   = "TransactionActionSheet.Title.SendMoney"
    case transactionActionSheetTitleAskForMoney                                 = "TransactionActionSheet.Title.AskForMoney"
    case transactionActionSheetTitleTransactions                                = "TransactionActionSheet.Title.Transactions"
    case financeGuruActionSheetTitleInsurance                                   = "FinanceGuruActionSheet.Title.Insurance"
    case financeGuruActionSheetTitleExtraLimit                                  = "FinanceGuruActionSheet.Title.ExtraLimit"
    case financeGuruActionSheetTitleFinanceGuru                                 = "FinanceGuruActionSheet.Title.FinanceGuru"
    case loadMoneyTitleNavigationTitle                                          = "LoadMoney.Title.NavigationTitle"
    case loadMoneyTitleLoadWithCard                                             = "LoadMoney.Title.LoadWithCard"
    case loadMoneyTitleLoadBankAccount                                          = "LoadMoney.Title.LoadBankAccount"
    case loadMoneyTitleLoadAutomatic                                            = "LoadMoney.Title.LoadAutomatic"
    
    case loadMoneyLoadWithDebitCreditCardTitleUnSuccessFullLoad                  = "LoadMoneyLoadWithDebitCreditCard.Title.UnSuccessFullLoad"
    case loadMoneyLoadWithDebitCreditCardTitleSuccessFullLoad                   = "LoadMoneyLoadWithDebitCreditCard.Title.SuccessFullLoad"
    case loadMoneyLoadWithDebitCreditCardTitleChooseAmount                      = "LoadMoneyLoadWithDebitCreditCard.Title.ChooseAmount"
    case loadMoneyLoadWithDebitCreditCardTitleChoosePaymentMethod               = "LoadMoneyLoadWithDebitCreditCard.Title.ChoosePaymentMethod"
    case loadMoneyLoadWithDebitCreditCardTitleLoadWithCard                      = "LoadMoneyLoadWithDebitCreditCard.Title.LoadWithCard"
    case loadMoneyLoadWithDebitCreditCardTitleRemainingUploadLimit              = "LoadMoneyLoadWithDebitCreditCard.Title.RemainingUploadLimit"
    case loadMoneyLoadWithDebitCreditCardTitlePayWithDifferentCard              = "LoadMoneyLoadWithDebitCreditCard.Title.IWantPayWithDifferentCard"
    case loadMoneyLoadWithDebitCreditCardTitleChangeCard                        = "LoadMoneyLoadWithDebitCreditCard.Title.ChangeCard"
    case loadMoneyLoadWithDebitCreditCardTitleOtherAmount                       = "LoadMoneyLoadWithDebitCreditCard.Title.OtherAmount"
    case loadMoneyLoadWithDebitCreditCardTitleAccountName                       = "LoadMoneyLoadWithDebitCreditCard.Title.AccountName"
    case storedCardTitleAddCard                                                 = "StoredCard.Title.AddCard"
    case storedCardTitleMySavedCards                                            = "StoredCard.Title.MySavedCards"
    case cardInformationScreenTitleCardInfo                                     = "CardInformationScreen.Title.CardInfo"
    case cardInformationScreenTextNameSurname                                   = "CardInformationScreen.Text.NameSurname"
    case cardInformationScreenTextCardOwner                                     = "CardInformationScreen.Text.CardOwner"
    case cardInformationScreenTextCardNumber                                    = "CardInformationScreen.Text.CardNumber"
    case cardInformationScreenTextExpirationDate                                = "CardInformationScreen.Text.ExpirationDate"
    case cardInformationScreenTextMonthYear                                     = "CardInformationScreen.Text.MonthYear"
    case cardInformationScreenTextStoreMyCard                                   = "CardInformationScreen.Text.StoreMyCard"
    case cardInformationScreenTextWhatIsMasterPass                              = "CardInformationScreen.Text.WhatIsMasterPass"
    case cardInformationScreenTextCardName                                      = "CardInformationScreen.Text.CardName"
    case cardInformationScreenTextNameYourCard                                  = "CardInformationScreen.Text.GiveNameYourCard"
    case cardInformationScreenTextMasterCardInfo                                = "CardInformationScreen.Text.MasterCardInfo"
    case transactionSummaryScreenTextPaymentTool                                = "TransactionSummaryScreen.Text.PaymentTool"
    case transactionSummaryScreenTextAccountToLoad                              = "TransactionSummaryScreen.Text.AccountToLoad"
    case transactionSummaryScreenTextAmountToCharge                             = "TransactionSummaryScreen.Text.AmountToCharge"
    case transactionSummaryScreenTextProcessingFee                              = "TransactionSummaryScreen.Text.ProcessingFee"
    case transactionSummaryScreenTextTotalAmount                                = "TransactionSummaryScreen.Text.TotalAmount"
    case transactionSummaryScreenTextOTPCode                                    = "TransactionSummaryScreen.Text.OTPCode"
    case customLoadingProgressViewTextPleaseWait                                = "CustomLoadingProgressView.Text.PleaseWait"
    case remainingLimitCardViewTextRemainingLimit                               = "RemainingLimitCardView.Text.RemainingLimit"
    case remainingLimitCardViewTextDailyRemainingLimit                          = "RemainingLimitCardView.Text.DailyRemainingLimit"
    case remainingLimitCardViewTextMonthlyRemainingLimit                        = "RemainingLimitCardView.Text.MonthlyRemainingLimit"
    case loadFromBankAccountTextDescription                                     = "LoadFromBankAccount.Text.Description"
    case loadFromBankAccountTextHowToLoad                                       = "LoadFromBankAccount.Text.HowToLoad"
    case loadFromBankAccountTitleLoadFromBankAccount                            = "LoadFromBankAccount.Title.LoadFromBankAccount"
    case loadFromBankAccountTextDailyRemainingLimit                             = "LoadFromBankAccount.Text.DailyRemainingLimit"
    case loadFromBankAccountTextMonthlyRemainingLimit                           = "LoadFromBankAccount.Text.MonthlyRemainingLimit"
    case loadFromBankAccountTextDailyLimitInfoPopUp                             = "LoadFromBankAccount.Text.DailyLimitInfoPopUp"
    case loadFromBankAccountTextMonthlyLimitInfoPopUp                           = "LoadFromBankAccount.Text.MonthlyLimitInfoPopUp"
    case loadFromBankAccountHeaderAndCardViewTextLoadFromBankAccount            = "LoadFromBankAccountHeaderAndCardView.Text.LoadFromBankAccount"
    case loadFromBankAccountHeaderAndCardViewTextReceiverName                   = "LoadFromBankAccountHeaderAndCardView.Text.ReceiverName"
    case loadFromBankAccountHeaderAndCardViewTextBank                           = "LoadFromBankAccountHeaderAndCardView.Text.Bank"
    case loadFromBankAccountHeaderAndCardViewTextDGparaPayment                  = "LoadFromBankAccountHeaderAndCardView.Text.DGparaPaymentAndElectronicMoney"
    case howToLoadMoneyFromAccountTitleTab1Title                                = "HowToLoadMoneyFromAccount.Title.Tab1Title"
    case howToLoadMoneyFromAccountTextTab1Description                           = "HowToLoadMoneyFromAccount.Text.Tab1Description"
    case howToLoadMoneyFromAccountTitleTab2Title                                = "HowToLoadMoneyFromAccount.Title.Tab2Title"
    case howToLoadMoneyFromAccountTextTab2Description                           = "HowToLoadMoneyFromAccount.Text.Tab2Description"
    case howToLoadMoneyFromAccountTitleTab3Title                                = "HowToLoadMoneyFromAccount.Title.Tab3Title"
    case howToLoadMoneyFromAccountTextTab3Description                           = "HowToLoadMoneyFromAccount.Text.Tab3Description"
    case howToLoadMoneyFromAccountTitleTab4Title                                = "HowToLoadMoneyFromAccount.Title.Tab4Title"
    case howToLoadMoneyFromAccountTextTab4Description                           = "HowToLoadMoneyFromAccount.Text.Tab4Description"
    case howToLoadMoneyFromAccountTitleHowToLoad                                = "HowToLoadMoneyFromAccount.Title.HowToLoad"
    case askForMoneyContactsToZubizuTextChooseThePerson                         = "AskForMoneyContactsToZubizu.Text.ChooseThePerson"
    case askForMoneyContactsToZubizuTextChooseThePersonNumber                   = "AskForMoneyContactsToZubizu.Text.ChooseThePersonNumber"
    case askForMoneyContactsToZubizuTextAskForMoneySuccessful                   =  "AskForMoneyContactsToZubizu.Text.AskForMoneySuccessful"
    case sendMoneyAcceptedContactsToZubizuTextChooseThePerson                   = "SendMoneyAcceptedContactsToZubizu.Text.ChooseThePerson"
    case sendMoneyAcceptedContactsToZubizuTextChooseThePersonNumber             = "SendMoneyAcceptedContactsToZubizu.Text.ChooseThePersonNumber"
    case sendMoneyAcceptedContactsToZubizuTextEnterTheNumber                    = "SendMoneyAcceptedContactsToZubizu.Text.EnterTheNumber"
    case sendMoneyAcceptedContactsToZubizuTextMyPhoneDirectory                  = "SendMoneyAcceptedContactsToZubizu.Text.MyPhoneDirectory"
    case sendMoneyAcceptedContactsToZubizuTextPersmissionDenied                 = "SendMoneyAcceptedContactsToZubizu.Text.PersmissionDenied"
    case sendMoneyAcceptedContactsToZubizuTextUnkownError                       = "SendMoneyAcceptedContactsToZubizu.Text.UnkownError"
    case sendMoneyAcceptedContactsToZubizuTextInfoAlertText                     = "SendMoneyAcceptedContactsToZubizu.Text.InfoAlertText"
    case sendMoneyAcceptedContactsToZubizuTextSearch                            = "SendMoneyAcceptedContactsToZubizu.Text.Search"
    case sendMoneyScreenTextSendNow                                             = "SendMoneyScreen.Text.SendNow"
    case sendMoneyScreenTextSendLater                                           = "SendMoneyScreen.Text.SendLater"
    case sendMoneyScreenTextGiveRegularInstruction                              = "SendMoneyScreen.Text.GiveRegularInstruction"
    case sendMoneyScreenTextSendMoney                                           = "SendMoneyScreen.Text.SendMoney"
    case communicationPreferencesScreenTitleNavigationTitle                     = "CommunicationPreferencesScreen.Title.NavigationTitle"
    case communicationPreferencesScreenTitleSMS                                 = "CommunicationPreferencesScreen.Title.SMS"
    case communicationPreferencesScreenTextAllowSms                             = "CommunicationPreferencesScreen.Text.AllowSms"
    case communicationPreferencesScreenTitleEmail                               = "CommunicationPreferencesScreen.Title.Email"
    case communicationPreferencesScreenTextAllowEmail                           = "CommunicationPreferencesScreen.Text.AllowEmail"
    case communicationPreferencesScreenTitlePhone                               = "CommunicationPreferencesScreen.Title.Phone"
    case communicationPreferencesScreenTextAllowPhone                           = "CommunicationPreferencesScreen.Text.AllowPhone"
    case currentPariodTransactionsScreenTextAvailableBalance                    = "CurrentPariodTransactionsScreen.Text.AvailableBalance"
    case currentPariodTransactionsScreenTitleSplitSpending                      = "CurrentPariodTransactionsScreen.Title.SplitSpending"
    case currentPariodTransactionsScreenTitleReceipt                            = "CurrentPariodTransactionsScreen.Title.Receipt"
    case currentPariodTransactionsScreenTextTotalSpending                       = "CurrentPariodTransactionsScreen.Text.TotalSpending"
    case feesAndLimitsScreenTitleNavigationTitle                                = "FeesAndLimitsScreen.Title.NavigationTitle"
    case feesAndLimitsScreenTitleAccountLimits                                  = "FeesAndLimitsScreen.Title.AccountLimits"
    case feesAndLimitsScreenTitleTransactionFees                                = "FeesAndLimitsScreen.Title.TransactionFees"
    case homeScreenTabViewTitleMicroCredit                                      = "HomeScreenTabView.Title.MicroCredit"
    case homeScreenTabViewTitlePendingTransactions                              = "HomeScreenTabView.Title.PendingTransactions"
    case homeScreenTabViewTitleTransactionHistory                               = "HomeScreenTabView.Title.TransactionHistory"
    case incomingAskForMoneyAcceptTextMoneyRequest                              = "IncomingAskForMoneyAccept.Text.MoneyRequest"
    case incomingAskForMoneyAcceptTextExplanation                               = "IncomingAskForMoneyAccept.Text.Explanation"
    case incomingAskForMoneyAcceptTextAmount                                    = "IncomingAskForMoneyAccept.Text.Amount"
    case incomingAskForMoneyAcceptTextTransactionFee                            = "IncomingAskForMoneyAccept.Text.TransactionFee"
    case incomingAskForMoneyAcceptTextTotalAmount                               = "IncomingAskForMoneyAccept.Text.TotalAmount"
    case incomingAskForMoneyAcceptTextDate                                      = "IncomingAskForMoneyAccept.Text.Date"
    case incomingAskForMoneyAcceptTextEnterExplanation                          = "IncomingAskForMoneyAccept.Text.EnterExplanation"
    case incomingSplitTheBillDetailTextSharedSpend                              = "IncomingSplitTheBillDetail.Text.SharedSpend"
    case incomingSplitTheBillDetailTextTransactionFee                           = "IncomingSplitTheBillDetail.Text.TransactionFee"
    case incomingSplitTheBillDetailTextTotalAmount                              = "IncomingSplitTheBillDetail.Text.TotalAmount"
    case outGoingAskForMoneyDetailTitleMoneyRequest                             = "OutGoingAskForMoneyDetail.Title.MoneyRequest"
    case outGoingAskForMoneyDetailTitleSelectedContacts                         = "OutGoingAskForMoneyDetail.Title.SelectedContacts"
    case outGoingAskForMoneyDetailTextSharedSpend                               = "OutGoingAskForMoneyDetail.Text.SharedSpend"
    case qrPaymentScreenTitleScanQr                                             = "QrPaymentScreen.Title.ScanQr"
    case qrPaymentScreenTextCancellationAmount                                  = "QrPaymentScreen.Text.CancellationAmount"
    case qrPaymentScreenTextRefoundAmount                                       = "QrPaymentScreen.Text.RefoundAmount"
    case qrPaymentScreenTextPaymentMethod                                       = "QrPaymentScreen.Text.PaymentMethod"
    case qrTransactionSummaryTitleScanQr                                        = "QrTransactionSummary.Title.ScanQr"
    case qrTransactionSummaryTextPaymentMethod                                  = "QrTransactionSummary.Text.PaymentMethod"
    case qrWithDrawMoneyScreenTitleSendNow                                      = "QrWithDrawMoneyScreen.Title.SendNow"
    case qrWithDrawMoneyScreenTextPaymentMethod                                 = "QrWithDrawMoneyScreen.Text.PaymentMethod"
    case qrWithDrawMoneyScreenTextVirtualCard                                   = "QrWithDrawMoneyScreen.Text.VirtualCard"
    case qrWithDrawMoneyScreenTextCurrentBalance                                = "QrWithDrawMoneyScreen.Text.CurrentBalance"
    case qrWithDrawMoneyScreenTextWithdrawalMethod                              = "QrWithDrawMoneyScreen.Text.WithdrawalMethod"
    case qrWithDrawMoneyScreenTextDailyWithdrawLimit                            = "QrWithDrawMoneyScreen.Text.DailyWithdrawLimit"
    case qrWithDrawMoneyScreenTextMonthlyWithdrawLimit                          = "QrWithDrawMoneyScreen.Text.MonthlyWithdrawLimit"
    case qrWithDrawMoneyScreenTextEnterAmount                                   = "QrWithDrawMoneyScreen.Text.EnterAmount"
    case qrWithDrawMoneyScreenTextViewFeeFromAtm                                = "QrWithDrawMoneyScreen.Text.ViewFeeFromAtm"
    case qrWithDrawMoneyScreenTextOther                                         = "QrWithDrawMoneyScreen.Text.Other"
    case sendMoneyAmountAndDescriptionTextEnterAmountAndDescription             = "SendMoneyAmountAndDescription.Text.EnterAmountAndDescription"
    case sendMoneyAmountAndDescriptionTextAvailableBalance                      = "SendMoneyAmountAndDescription.Text.AvailableBalance"
    case sendMoneyAmountAndDescriptionTextEnterExplanation                      = "SendMoneyAmountAndDescription.Text.EnterExplanation"
    case sendMoneyIbanTabScreenTitleSendMoney                                   = "SendMoneyIbanTabScreen.Title.SendMoney"
    case sendMoneyIbanTabScreenTitleHowSendMoneyToIban                          = "SendMoneyIbanTabScreen.Title.HowSendMoneyToIban"
    case sendMoneyIbanTabScreenTitleSenderInformation                           = "SendMoneyIbanTabScreen.Title.SenderInformation"
    case sendMoneyIbanTabScreenTitleAvailableWalletAmount                       = "SendMoneyIbanTabScreen.Title.AvailableWalletAmount"
    case sendMoneyIbanTabScreenTitleRecipientInfo                               = "SendMoneyIbanTabScreen.Title.RecipientInfo"
    case sendMoneyIbanTabScreenTitleRecipientIban                               = "SendMoneyIbanTabScreen.Title.RecipientIban"
    case sendMoneyIbanTabScreenTitleRecipientNameSurname                        = "SendMoneyIbanTabScreen.Title.RecipientNameSurname"
    case sendMoneyIbanTabScreenTitleTransactionInformation                      = "SendMoneyIbanTabScreen.Title.TransactionInformation"
    case sendMoneyIbanTabScreenTitleTransactionDate                             = "SendMoneyIbanTabScreen.Title.TransactionDate"
    case sendMoneyIbanTabScreenTitleTransactionType                             = "SendMoneyIbanTabScreen.Title.TransactionType"
    case sendMoneySuccesfullTextYourTransactionSuccessful                       = "SendMoneySuccesfull.Text.YourTransactionSuccessful"
    case sendMoneySuccesfullTextYourMoneyTransferWasSuccessful                  = "SendMoneySuccesfull.Text.YourMoneyTransferWasSuccessful"
    case sendMoneySuccesfullTextShowReceipt                                     = "SendMoneySuccesfull.Text.ShowReceipt"
    case sendMoneySuccesfullTextShareReceipt                                    = "SendMoneySuccesfull.Text.ShareReceipt"
    case sendMoneySuccesfullTextReceipt                                         = "SendMoneySuccesfull.Text.Receipt"
    case sendMoneyToIbanTransactionSummarySuccessful                            = "SendMoneyToIbanTransactionSummary.Text.YourTransactionSuccessful"
    case sendMoneyToIbanTransactionSummaryTextRecipientInfo                     = "SendMoneyToIbanTransactionSummary.Text.RecipientInfo"
    case sendMoneyToIbanTransactionSummaryTextRecipientIban                     = "SendMoneyToIbanTransactionSummary.Text.RecipientIban"
    case sendMoneyToIbanTransactionSummaryTextRecipientNameSurname              = "SendMoneyToIbanTransactionSummary.Text.RecipientNameSurname"
    case sendMoneyToIbanTransactionSummaryTextRecipientBankIban                 = "SendMoneyToIbanTransactionSummary.Text.RecipientBankIban"
    case sendMoneyToIbanTransactionSummaryTextTransactionInformation            = "SendMoneyToIbanTransactionSummary.Text.TransactionInformation"
    case sendMoneyToIbanTransactionSummaryTextDate                              = "SendMoneyToIbanTransactionSummary.Text.Date"
    case sendMoneyToIbanTransactionSummaryTextTransactionType                   = "SendMoneyToIbanTransactionSummary.Text.TransactionType"
    case sendMoneyToIbanTransactionSummaryTextTransactionExplanation            = "SendMoneyToIbanTransactionSummary.Text.TransactionExplanation"
    case settingsScreenTitleSettings                                            = "SettingsScreen.Title.Settings"
    case settingsScreenTitleProfileInformation                                  = "SettingsScreen.Title.ProfileInformation"
    case settingsScreenTitleChangePassword                                      = "SettingsScreen.Title.ChangePassword"
    case settingsScreenTitleChangePhoneNumber                                   = "SettingsScreen.Title.ChangePhoneNumber"
    case settingsScreenTitleChangeLanguage                                      = "SettingsScreen.Title.ChangeLanguage"
    case settingsScreenTitleChangeSecretQuestion                                = "SettingsScreen.Title.ChangeSecretQuestion"
    case settingsScreenTitleCommunicationPreferences                            = "SettingsScreen.Title.CommunicationPreferences"
    case settingsScreenTitleExplicitConsentPreferences                          = "SettingsScreen.Title.ExplicitConsentPreferences"
    case splitTheBillPhoneSelectionScreenTextSelectWantToSplit                  = "SplitTheBillPhoneSelectionScreen.Text.SelectWantToSplit"
    case splitTheBillPhoneSelectionScreenTextEnterNumberToSplit                 = "SplitTheBillPhoneSelectionScreen.Text.EnterNumberToSplit"
    case splitTheBillPhoneSelectionScreenTextAdd                                = "SplitTheBillPhoneSelectionScreen.Text.Add"
    case splitTheBillPhoneSelectionScreenTextPeopleYouWantToAllocate            = "SplitTheBillPhoneSelectionScreen.Text.PeopleYouWantToAllocateYourExpensesTo"
    case splitTheBillPhoneSelectionScreenTextPersonAdded                        = "SplitTheBillPhoneSelectionScreen.Text.PersonAdded"
    case splitTheBillScreenTextReceipt                                          = "SplitTheBillScreen.Text.Receipt"
    case splittingScreenTextSpendToBeSplitting                                  = "SplittingScreen.Text.SpendToBeSplitting"
    case splittingScreenTextSelectedPerson                                      = "SplittingScreen.Text.SelectedPerson"
    case splittingScreenTextSplitEqual                                          = "SplittingScreen.Text.SplitEqual"
    case splittingScreenTextReceipt                                             = "SplittingScreen.Text.Receipt"
    case splittingScreenTextRemoveThePerson                                     = "SplittingScreen.Text.RemoveThePerson"
    case splittingScreenTextSpendingSplitList                                   = "SplittingScreen.Text.SpendingSplitList"
    case splittingScreenTextRemoved                                             = "SplittingScreen.Text.Removed"
    case splittingScreenTextAmountAlert                                         = "SplittingScreen.Text.AmountAlert"
    case splittingScreenTitleAmountAlert                                        = "SplittingScreen.Title.AmountAlert"
    case userAgreementScreenTitleUserAgreement                                  = "UserAgreementScreen.Title.UserAgreement"
    case userAgreementScreenTitleIConfirm                                       = "UserAgreementScreen.Title.IConfirm"
    case userAgreementScreenTitleIConfirmText                                   = "UserAgreementScreen.Title.IConfirmText"
    case createSecretQuestionScreenTitleChangeSecretQuestion                    = "CreateSecretQuestionScreen.Title.ChangeSecretQuestion"
    case createSecretQuestionScreenTextNewSecretQuestion                        = "CreateSecretQuestionScreen.Text.NewSecretQuestion"
    case createSecretQuestionScreenTextAnswerOfQuestion                         = "CreateSecretQuestionScreen.Text.AnswerOfQuestion"
    case createSecretQuestionScreenTextSecretQuestionAnswer                     = "CreateSecretQuestionScreen.Text.SecretQuestionAnswerExplanation"
    case createSecretQuestionScreenTextAnswerOfSecretQuestion                   = "CreateSecretQuestionScreen.Text.AnswerOfSecretQuestion"
    case createSecretQuestionScreenTextFirstRule                                = "CreateSecretQuestionScreen.Text.FirstRule"
    case createSecretQuestionScreenTextCannotContainSpaces                      = "CreateSecretQuestionScreen.Text.CannotContainSpaces"
    case createSecretQuestionScreenTextMayContainSpacialCharacters              = "CreateSecretQuestionScreen.Text.MayContainSpacialCharacters"
    case changeSecretQuestionScreenTitleChangeSecretQuestion                    = "ChangeSecretQuestionScreen.Title.ChangeSecretQuestion"
    case changeSecretQuestionScreenTextCurrentSecretQuestion                    = "ChangeSecretQuestionScreen.Text.CurrentSecretQuestion"
    case changeSecretQuestionScreenTextAnswerOfQuestion                         = "ChangeSecretQuestionScreen.Text.AnswerOfQuestion"
    case changeSecretQuestionScreenTextIForgotTheAnswer                         = "ChangeSecretQuestionScreen.Text.IForgotTheAnswer"
    case openConsentPreferencesScreenTitleOpenConsentPreferances                = "OpenConsentPreferencesScreen.Title.OpenConsentPreferances"
    case openConsentPreferencesScreenTextPersonalizedAdvertising                = "OpenConsentPreferencesScreen.Text.PersonalizedAdvertising"
    case openConsentPreferencesScreenTextWalletPersonalizedAdv                  = "OpenConsentPreferencesScreen.Text.WalletPersonalizedAdvertising"
    case openConsentPreferencesScreenTextDataEnrichment                         = "OpenConsentPreferencesScreen.Text.DataEnrichment"
    case openConsentPreferencesScreenTextOwnerDataEnrichment                    = "OpenConsentPreferencesScreen.Text.OwnerDataEnrichment"
    case changePhoneNumberSecretQuestionScreenTitle                             = "ChangePhoneNumberSecretQuestionScreen.Title.ChangeSecretQuestion"
    case changePhoneNumberSecretQuestionScreenTextCurrent                       = "ChangePhoneNumberSecretQuestionScreen.Text.CurrentSecretQuestion"
    case changePhoneNumberSecretQuestionScreenTextAnswerOfQuestion              = "ChangePhoneNumberSecretQuestionScreen.Text.AnswerOfQuestion"
    case changePhoneNumberSecretQuestionScreenTextIForgotTheAnswer              = "ChangePhoneNumberSecretQuestionScreen.Text.IForgotTheAnswer"
    case profileInformationsScreenTitleMyProfileInformations                    = "ProfileInformationsScreen.Title.MyProfileInformations"
    case profileInformationsScreenTextName                                      = "ProfileInformationsScreen.Text.Name"
    case profileInformationsScreenTextSurname                                   = "ProfileInformationsScreen.Text.Surname"
    case profileInformationsScreenTextPhoneNumber                               = "ProfileInformationsScreen.Text.PhoneNumber"
    case profileInformationsScreenTextBirthDate                                 = "ProfileInformationsScreen.Text.BirthDate"
    case profileInformationsScreenTextEMail                                     = "ProfileInformationsScreen.Text.EMail"
    case profileInformationsScreenTextJob                                       = "ProfileInformationsScreen.Text.Job"
    case profileInformationsScreenTextMonthlyNetIncome                          = "ProfileInformationsScreen.Text.MonthlyNetIncome"
    case profileInformationsScreenTextEstimatedWalletBalance                    = "ProfileInformationsScreen.Text.EstimatedWalletBalance"
    case profileInformationsScreenTextMonthyTransactionCount                    = "ProfileInformationsScreen.Text.MonthyTransactionCount"
    case profileInformationsScreenTextRemoveAccount                             = "ProfileInformationsScreen.Text.RemoveAccount"
    case profileInformationsScreenTextWarning                                   = "ProfileInformationsScreen.Text.Warning"
    case profileInformationsScreenTextWarningText                               = "ProfileInformationsScreen.Text.WarningText"
    case failLoginAttempsSheetTextDate                                          = "FailLoginAttempsSheet.Text.Date"
    case failLoginAttempsSheetTextDescription                                   = "FailLoginAttempsSheet.Text.Description"
    case failLoginAttempsSheetTextFailLoginAttemp                               = "FailLoginAttempsSheet.Text.FailLoginAttemp"
    case failLoginAttempsSheetTitleLoginAttemps                                 = "FailLoginAttempsSheet.Title.LoginAttemps"
    case myWalletInfoScreenTitleWalletInfo                                      = "MyWalletInfoScreen.Title.WalletInfo"
    case myWalletInfoScreenTextMoneyInputZubizuWallet                           = "MyWalletInfoScreen.Text.MoneyInputZubizuWallet"
    case myWalletInfoScreenLimitCardViewTextDaily                               = "MyWalletInfoScreen.LimitCardView.Text.Daily"
    case myWalletInfoScreenLimitCardViewTextMonthly                             = "MyWalletInfoScreen.LimitCardView.Text.Monthly"
    case myWalletInfoScreenCardLimitViewTextAmountLimit                         = "MyWalletInfoScreen.CardLimitView.Text.AmountLimit"
    case myWalletInfoScreenCardLimitViewTextQuantityLimit                       = "MyWalletInfoScreen.CardLimitView.Text.QuantityLimit"
    case notificationsTitle                                                     = "Notifications.Title"
    case notificationsTextEmptyNotifications                                    = "Notifications.Text.EmptyNotifications"
    case aboutWhiteLabelTitle                                                   = "AboutWhiteLabel.Title"
    case aboutWhiteLabelTextFrequenltyAskedQuestions                            = "AboutWhiteLabel.Text.FrequenltyAskedQuestions"
    case aboutWhiteLabelTextCookie                                              = "AboutWhiteLabel.Text.Cookie"
    case aboutWhiteLabelTextClarification                                       = "AboutWhiteLabel.Text.Clarification"
    case aboutWhiteLabelTextPersonalData                                        = "AboutWhiteLabel.Text.PersonalData"
    case aboutWhiteLabelTextRepresentativeInfo                                  = "AboutWhiteLabel.Text.RepresentativeInfo"
    case aboutWhiteLabelTextRemindMe                                            = "AboutWhiteLabel.Text.RemindMe"
    case aboutWhiteLabelTextDgpPara                                             = "AboutWhiteLabel.Text.DgpPara"
    case aboutWhiteLabelTextUserAgreement                                       = "AboutWhiteLabel.Text.UserAgreement"
    case aboutWhiteLabelTextWhatIs                                              = "AboutWhiteLabel.Text.WhatIs"
    case aboutWhiteLabelTextContactUs                                           = "AboutWhiteLabel.Text.ContactUs"
    case aboutWhiteLabelTextSuggestion                                          = "AboutWhiteLabel.Text.Suggestion"
    case verifyIdentityTitle                                                    = "VerifyIdentity.Title"
    case verifyIdentityTextLoadMoney                                            = "VerifyIdentity.Text.LoadMoney"
    case verifyIdentityTitlekyc1                                                = "VerifyIdentity.Title.kyc_1"
    case verifyIdentityTextkyc1                                                 = "VerifyIdentity.Text.kyc_1"
    case verifyIdentityTitlekyc2                                                = "VerifyIdentity.Title.kyc_2"
    case verifyIdentityTextkyc2                                                 = "VerifyIdentity.Text.kyc_2"
    case verifyIdentityTitlestep1                                               = "VerifyIdentity.Title.step_1"
    case verifyIdentityTitlestep2                                               = "VerifyIdentity.Title.step_2"
    case verifyIdentityTitlestep3                                               = "VerifyIdentity.Title.step_3"
    case verifyIdentityTitlestep4                                               = "VerifyIdentity.Title.step_4"
    case verifyIdentityTitlestep5                                               = "VerifyIdentity.Title.step_5"
    case verifyIdentityTextheader                                               = "VerifyIdentity.Text.header"
    case permissionsTitleLocation                                               = "Permissions.Title.Location"
    case permissionsTitleOpenLocation                                           = "Permissions.Title.OpenLocation"
    case permissionsTitleOpenCamera                                             = "Permissions.Title.OpenCamera"
    case permissionsTextLocation                                                = "Permissions.Text.Location"
    case permissionsTextCamera                                                  = "Permissions.Text.Camera"
    case virtualCardTitlefirstText                                              = "VirtualCard.Title.firstText"
    case virtualCardTitlesecondText                                             = "VirtualCard.Title.secondText"
    case savedCardsTitleslideButtonText                                         = "SavedCards.Title.slideButtonText"
    case savedCardsTitlenavigationTitle                                         = "SavedCards.Title.navigationTitle"
    case savedCardsTitleWlCards                                                 = "SavedCards.Title.WlCards"
    case savedCardsTitlesavedCards                                              = "SavedCards.Title.savedCards"
    case savedCardsTitlebankAccounts                                            = "SavedCards.Title.bankAccounts"
    case savedCardsTitleaddCard                                                 = "SavedCards.Title.addCard"
    case savedCardsTitleaddWlblwCard                                            = "SavedCards.Title.addWlblwCard"
    case savedCardsTitlenotFindCard                                             = "SavedCards.Title.notFindCard"
    case savedCardsTitlecardSuccessDeleted                                      = "SavedCards.Title.cardSuccessDeleted"
    case savedCardsTitleareYouSureDeleteCard                                    = "SavedCards.Title.areYouSureDeleteCard"
    case savedCardsTitledeleteCard                                              = "SavedCards.Title.deleteCard"
    case savedCardsTextnoRegisteredCard                                         = "SavedCards.Text.noRegisteredCard"
    case masterPassTitlealertTitle                                              = "MasterPass.Title.alertTitle"
    case masterPassTitlealertText                                               = "MasterPass.Title.alertText"
    case masterPassTitleotp                                                     = "MasterPass.Title.otp"
    case masterPassTitleotpText                                                 = "MasterPass.Title.otpText"
    case masterPassTitleTitlenavigationTitle                                    = "MasterPass.Title.Title.navigationTitle"
    case masterPassTitlecardName                                                = "MasterPass.Title.cardName"
    case masterPassTitlegiveCardName                                            = "MasterPass.Title.giveCardName"
    case masterPassTitleaddCardToMasterPass                                     = "MasterPass.Title.addCardToMasterPass"
    case masterPassTitleWrongCardNumber                                         = "MasterPass.Title.WrongCardNumber"
    case cashLimitTextalertText                                                 = "CashLimit.Text.alertText"
    case cashLimitTitlenavigationTitle                                          = "CashLimit.Title.navigationTitle"
    case cashLimitTextbuttonText                                                = "CashLimit.Text.buttonText"
    case cashLimitTextalertDialogText                                           = "CashLimit.Text.alertDialogText"
    case cashLimitTitlealertDialogTitle                                         = "CashLimit.Title.alertDialogTitle"
    case cashLimitTitletoggle                                                   = "CashLimit.Title.toggle"
    case cashLimitTexttextfieldHeader                                           = "CashLimit.Text.textfieldHeader"
    case cashLimitTitlelimitTitle                                               = "CashLimit.Title.limitTitle"
    case cashLimitTitleUpdateLimitTitle                                         = "CashLimit.Title.UpdateLimitTitle"
    case cashLimitTextlimitText                                                 = "CashLimit.Text.limitText"
    case cashLimitTextdisableLimitText                                          = "CashLimit.Text.disableLimitText"
    case cashLimitTitledisableLimitTitle                                        = "CashLimit.Title.disableLimitTitle"
    case cashLimitTitleaddLimitSuccessTitle                                     = "CashLimit.Title.addLimitSuccessTitle"
    case cashLimitTextaddLimitSuccessText                                       = "CashLimit.Text.addLimitSuccessText"
    case cashLimitTitleremoveLimitSuccessTitle                                  = "CashLimit.Title.removeLimitSuccessTitle"
    case cashLimitTextremoveLimitSuccessText                                    = "CashLimit.Text.removeLimitSuccessText"
    case cashLimitTextAbort                                                     = "CashLimit.Text.Abort"
    case monthlyLimitTextalertText                                              = "MonthlyLimit.Text.alertText"
    case monthlyLimitTitlenavigationTitle                                       = "MonthlyLimit.Title.navigationTitle"
    case monthlyLimitTitletoggle                                                = "MonthlyLimit.Title.toggle"
    case monthlyLimitTexttextfieldHeader                                        = "MonthlyLimit.Text.textfieldHeader"
    case monthlyLimitUpdateLimitTitle                                           = "MonthlyLimit.Title.UpdateLimitTitle"
    case monthlyLimitTitledisableLimitTitle                                     = "MonthlyLimit.Title.disableLimitTitle"
    case monthlyLimitTitleYourLimitHasBeenUpdated                               = "MonthlyLimit.Title.YourLimitHasBeenUpdated"
    case monthlyLimitTextUpdatedLimitSuccessText                                = "MonthlyLimit.Text.updatedLimitSuccessText"
    case myWLCardsTextlastCard                                                  = "MyWLCards.Text.lastCard"
    case virtualCardsTitleNavigationTitle                                       = "VirtualCards.Title.NavigationTitle"
    case virtualCardsTextLoadMoneyToCard                                        = "VirtualCards.Text.LoadMoneyToCard"
    case virtualCardsTextShare                                                   = "VirtualCards.Text.Share"
    case virtualCardsTextCardSettings                                            = "VirtualCards.Text.CardSettings"
    case virtualCardsTextSharePeriodTransaction                                 = "VirtualCards.Text.SharePeriodTransaction"
    case virtualCardsTextGetEmail                                               = "VirtualCards.Text.GetEmail"
    case virtualCardsTitleSuccesFullySended                                     = "VirtualCards.Title.SuccesFullySended"
    case virtualCardsTitleVerifyEmail                                           = "VirtualCards.Title.VerifyEmail"
    case virtualCardsTextVerifyEmail                                            = "VirtualCards.Text.VerifyEmail"
    case myProfileScreenTitleNavigationTitle                                    = "MyProfileScreen.Title.NavigationTitle"
    case allTransactionsHistoryScreenTitleTabBarFirst                           = "AllTransactionsHistoryScreen.Title.TabBarFirst"
    case allTransactionsHistoryScreenTitleTabBarSecond                          = "AllTransactionsHistoryScreen.Title.TabBarSecond"
    case allTransactionsHistoryScreenTextEMail                                  = "AllTransactionsHistoryScreen.Text.EMail"
    case shareAndTakeEmailPopUpTextChooseDate                                   = "ShareAndTakeEmailPopUp.Text.ChooseDate"
    case shareAndTakeEmailPopUpTextGetEmail                                     = "ShareAndTakeEmailPopUp.Text.GetEmail"
    case accountInformationPopupAccountType                                     = "AccountInformationPopup.Text.AccountType"
    case accountInformationPopupTurkishLiraAccount                              = "AccountInformationPopup.Text.TurkishLiraAccount"
    case accountInformationPopupTotalBalance                                    = "AccountInformationPopup.Text.TotalBalance"
    case accountInformationPopupCashWithdrawableBalance                         = "AccountInformationPopup.Text.CashWithdrawableBalance"
    case accountInformationPopupAccountInformation                              = "AccountInformationPopup.Text.AccountInformation"
    case accountInformationPopupTLCashWithdrawableBalance                       = "AccountInformationPopup.Text.TLCashWithdrawableBalance"
    case accountInformationPopupTLCashWithdrawableBalanceDesc = "AccountInformationPopup.Text.TLCashWithdrawableBalanceDesc"
    case arafCardViewTextInfo                                                   = "ArafCardView.Text.Info"
    case arafCardViewTextAraf                                                   = "ArafCardView.Text.Araf"
    case cardSettingsMonthlyExpenditureLimitNotification                        = "CardSettings.Text.MonthlyExpenditureLimitNotification"
    case cardSettingsCashWithdrawalLimitNotification                            = "CardSettings.Text.CashWithdrawalLimitNotification"
    case cardSettingsDomesticCashWithdrawal                                     = "CardSettings.Text.DomesticCashWithdrawal"
    case cardSettingsCashWithdrawalAbroad                                       = "CardSettings.Text.CashWithdrawalAbroad"
    case cardSettingsDomesticTelephoneEMailExchange                             = "CardSettings.Text.DomesticTelephoneEMailExchange"
    case cardSettingsOverseasTelephoneEMailExchange                             = "CardSettings.Text.OverseasTelephoneEMailExchange"
    case cardSettingsDomesticECommerce                                          = "CardSettings.Text.DomesticECommerce"
    case cardSettingsOverseasECommerce                                          = "CardSettings.Text.OverseasECommerce"
    case cardSettingsExpenditureAbroad                                          = "CardSettings.Text.ExpenditureAbroad"
    case cardSettingsTemporarilyCloseMyCard                                     = "CardSettings.Text.TemporarilyCloseMyCard"
    case cardSettingsCardSettings                                               = "CardSettings.Text.CardSettings"
    case myProfileSettings                                                      = "MyProfile.Text.Settings"
    case myProfileNotifications                                                 = "MyProfile.Text.Notifications"
    case myProfileMyWalletInformation                                           = "MyProfile.Text.MyWalletInformation"
    case myProfileFeesAndLimits                                                 = "MyProfile.Text.FeesAndLimits"
    case myProfileAboutWhiteLabel                                               = "MyProfile.Text.AboutWhiteLabel"
    case myProfileSignOut                                                       = "MyProfile.Text.SignOut"
    case outGoingAskForMoneyDetailTextSuccessFullyCancel                        = "OutGoingAskForMoneyDetail.Text.SuccessFullyCancel"
    case sendMoneyNavigationBarForWhiteLabelUsers                               = "SendMoneyNavigationBar.Text.ForWhiteLabelUsers"
    case sendMoneyNavigationBarToIBAN                                           = "SendMoneyNavigationBar.Text.ToIBAN"
    case cardInformationScreenWLBLWAccount                                      = "CardInformationScreen.Text.WLBLWAccount"
    case splitTheBillSummaryScreenAcceptExplanation                             = "SplitTheBillSummaryScreen.Text.AcceptExplanation"
    
    // MARK: ChangePasswordScreen
    case changePasswordScreenNewPasswordAgain                                   = "ChangePasswordScreen.Text.NewPasswordAgain"
    case changePasswordScreenThePasswordsDidNotMatch                            = "ChangePasswordScreen.Text.ThePasswordsDidNotMatch"
    
    // MARK: InvoicedetailScreen
    case invoicedetailScreenInvoiceInformation                                  = "InvoicedetailScreen.Text.InvoiceInformation"
    case invoicedetailScreenNameOfInstitution                                   = "InvoicedetailScreen.Text.NameOfInstitution"
    case invoicedetailScreenSubscriberContractNo                                = "InvoicedetailScreen.Text.SubscriberContractNo"
    case invoicedetailScreenInsert                                              = "InvoicedetailScreen.Text.Insert"
    case invoicedetailScreenMustBeDigits                                        = "InvoicedetailScreen.Text.MustBeDigits"
    case invoicedetailScreenEnquire                                             = "InvoicedetailScreen.Text.Enquire"
    case invoicedetailScreenEsgazDisclaimer                                     = "InvoicedetailScreen.Text.EsgazDisclaimer"
    case invoicedetailScreenInvoiceAmount                                       = "InvoicedetailScreen.Text.InvoiceAmount"
    case invoicedetailScreenAmountToBePaid                                      = "InvoicedetailScreen.Text.AmountToBePaid"
    case invoicedetailScreenPaymentDeadline                                     = "InvoicedetailScreen.Text.PaymentDeadline"
    case invoicedetailScreenPaymentMethod                                       = "InvoicedetailScreen.Text.PaymentMethod"
    case invoicedetailScreenWLBLWWallet                                         = "InvoicedetailScreen.Text.WLBLWWallet"
    
    // MARK: InvoiceSummaryScreen
    case invoiceSummaryScreenInvoiceNo                                          = "InvoiceSummaryScreen.Text.InvoiceNo"
    
    // MARK: InvoiceGetInstitutionListScreen
    case invoiceGetInstitutionListScreenSearchByInstitutionName                 = "InvoiceGetInstitutionListScreen.Text.SearchByInstitutionName"
    case invoiceGetInstitutionListScreenEnterInstitutionName                    = "InvoiceGetInstitutionListScreen.Text.EnterInstitutionName"
    case invoiceGetInstitutionListScreenAllInstitutions                         = "InvoiceGetInstitutionListScreen.Text.AllInstitutions"
    
    // MARK: LoginWrongInformationView
    case loginWrongInformationViewYouHaveTheRightToTry                          = "LoginWrongInformationView.Text.YouHaveTheRightToTry"
    case loginWrongInformationViewVerificationMakingSure                        = "LoginWrongInformationView.Text.VerificationMakingSure"
    
    // MARK: PayBillScreen
    case payBillScreenAutomaticPaymentInstructions                              = "PayBillScreen.Text.AutomaticPaymentInstructions"
    
    // MARK: QrScreen
    case qrScreenHelloNameSurname                                               = "QrScreen.Text.HelloNameSurname"
    
    // MARK: - ResetPasswordFromEmail
    case resetPasswordFromEmailResetPassword                                    = "ResetPasswordFromEmail.Text.ResetPassword"
    
    // MARK: SelectInvoiceScreen
    case selectInvoiceScreenSelectTheInvoiceYouWantToPay                        = "SelectInvoiceScreen.Text.SelectTheInvoiceYouWantToPay"
    
    // MARK: IlluminationTextScreen
    case illuminationTextScreenDgParaClarificationText                          = "IlluminationTextScreen.Text.DgParaClarificationText"
    case illuminationTextScreenWLBLWClarificationText                           = "IlluminationTextScreen.Text.WLBLWClarificationText"
    
    // MARK: PaymentWithCardSelection
    case paymentWithCardSelectionShoppingAmount                                 = "PaymentWithCardSelection.Text.ShoppingAmount"
    
    // MARK: DatePickerSheet
    case datePickerSheetPleaseSelectTransactionDate                             = "DatePickerSheet.Text.PleaseSelectTransactionDate"
    
    // MARK: FilterResultEmpty
    case filterResultEmptyAccountcriteria                                       = "FilterResultEmpty.Text.Accountcriteria"
    
    // MARK: ShowQR
    case showQRQRCodeRenewal                                                    = "ShowQR.Text.QRCodeRenewal"
    case showQRWLBLWShowyourQRCode                                              = "ShowQR.Text.WLBLWShowyourQRCode"
    
    // MARK: CustomAlertViewDialog
    case customAlertViewDialogListingInMasterpass                               = "CustomAlertViewDialog.Text.ListingInMasterpass"
    
    // MARK: LogOutAlertView
    case logOutAlertViewAreYouSureYouWantToCheckOut                             = "LogOutAlertView.Text.AreYouSureYouWantToCheckOut"
    
    // MARK: SplitDialog
    case splitDialogDetermineTheAmountToBePaidByThePerson                       = "SplitDialog.Text.DetermineTheAmountToBePaidByThePerson"
    
    // MARK: EmailVerificationCardView
    case emailVerificationCardViewYourEmailIsVerified                           = "EmailVerificationCardView.Text.YourEmailIsVerified"
    case emailVerificationCardViewYourEmailIsNotVerified                        = "EmailVerificationCardView.Text.YourEmailIsNotVerified"
    
    // MARK: EmailVerificationSended
    case emailVerificationCardViewVerificationLinkSent                          = "EmailVerificationCardView.Text.VerificationLinkSent"
    
    // MARK: MyProfileVerificationCardView
    case myProfileVerificationCardViewIdentityVerified                          = "MyProfileVerificationCardView.Text.IdentityVerified"
    case myProfileVerificationCardViewVerifyYourIdentity                        = "MyProfileVerificationCardView.Text.VerifyYourIdentity"
    
    // MARK: PaymentTransactionSummaryCardView
    case paymentTransactionSummaryCardViewWorkplaceTitle                        = "PaymentTransactionSummaryCardView.Text.WorkplaceTitle"
    case paymentTransactionSummaryCardViewCardNumber                            = "PaymentTransactionSummaryCardView.Text.CardNumber"
    case paymentTransactionSummaryCardViewCancellationRefundAmount              = "PaymentTransactionSummaryCardView.Text.CancellationRefundAmount"
    case paymentTransactionSummaryCardViewTotalCancellation                     = "PaymentTransactionSummaryCardView.Text.TotalCancellationRefundAmount"
    
    // MARK: ProcessingFeeInsideCardView
    case paymentTransactionSummaryCardViewAmountLimit                           = "ProcessingFeeInsideCardView.Text.AmountLimit:"
    
    // MARK: ScanQrCardView
    case scanQrCardViewShoppingAndLoremIpsumDolorSitAmet                        = "ScanQrCardView.Text.ShoppingAndLoremIpsumDolorSitAmetConsecteturLoremIpsum"
    
    // MARK: ChoosenPeopleSplitRow
    case choosenPeopleSplitRowEditAmount                                        = "ChoosenPeopleSplitRow.Text.EditAmount"
    
    // MARK: SplitOutgoingRequestRow
    case splitOutgoingRequestRowONWAIT                                          = "SplitOutgoingRequestRow.Text.ONWAIT"
    case splitOutgoingRequestRowEXPIRED                                         = "SplitOutgoingRequestRow.Text.Expired"
    case splitOutgoingRequestRowREJECTED                                        = "SplitOutgoingRequestRow.Text.REJECTED"
    case splitOutgoingRequestRowACCEPTED                                        = "SplitOutgoingRequestRow.Text.ACCEPTED"
    
    // MARK: StoredCardViewRow
    case storedCardViewRowNoCardName                                            = "StoredCardViewRow.Text.NoCardName"
    
    // MARK: AllCardsTabViewModel
    case allCardsTabViewModelYourCardStatusHasBeenChanged                       =   "AllCardsTabViewModel.Text.YourCardStatusHasBeenChanged"
    
    // MARK: alertModel
    case alertModelYouAreGoingToCancelTheTransactionDoYouConfirm                = "alertModel.Text.YouAreGoingToCancelTheTransactionDoYouConfirm"
    case alertModelYoullCancelTheOperation                                      = "alertModel.Text.YoullCancelTheOperation"
    case alertModelYourPasswordHasBeenSuccessfullyUpdated                       = "alertModel.Text.YourPasswordHasBeenSuccessfullyUpdated"
    case alertModelYourPhoneNumberHasBeenSuccessfullyChanged                    = "alertModel.Text.YourPhoneNumberHasBeenSuccessfullyChanged"
    case alertModelOtpExpired                                                   = "alertModel.title.OtpExpired"
    case alertModelOtpExpiredPleaseRequestACodeAgain                            = "alertModel.Text.OtpExpiredPleaseRequestACodeAgain"
    case alertModelTryAgain                                                     = "alertModel.Text.TryAgain"
    case alertModelYouCanNowUseYourNewSecurityQuestionInWhitelbl                = "alertModel.Text.YouCanNowUseYourNewSecurityQuestionInWhitelbl"
    case alertModelSuccessfullyModifiedYourSecurityQuestion                     = "alertModel.title.SuccessfullyModifiedYourSecurityQuestion"
    
    case alertModelCameraPermissionNotFoundPleaseAuthoriseCamera                = "alertModel.Text.CameraPermissionNotFoundPleaseAuthoriseCamera"
    case alertModelQRCodeNotRead                                                = "alertModel.Text.QRCodeNotRead"
    case alertModelUnknownError                                                 = "alertModel.Text.UnknownError"
    case alertModelQrWrongFormat                                                = "alertModel.Text.QrWrongFormat"
    case alertModelYourWithdrawalIsSuccessfulYouCanContinueAtTheATM             = "alertModel.Text.YourWithdrawalIsSuccessfulYouCanContinueYourTransactionAtTheATM"
    case alertModelYourCommunicationPreferencesUpdateHaveBeenSuccess            = "alertModel.Text.YourCommunicationPreferencesHaveBeenSuccessfullyUpdated"
    case alertModelWalletError                                                  = "alertModel.Text.WalletError"
    case alertModelYourMoneyTransferWasSuccessful                               = "alertModel.Text.YourMoneyTransferWasSuccessful"
    case alertModelRequestRejected                                              = "alertModel.title.RequestRejected"
    case alertModelTheRequestWasSuccessfullyRejected                            = "alertModel.Text.TheRequestWasSuccessfullyRejected"
    case alertModelYourOpenConsentPreferencesSuccessfullyUpdated                = "alertModel.Text.YourOpenConsentPreferencesSuccessfullyUpdated"
    case alertModelConfirmIfYouWantToCancelTheExpenseSplitRequest               = "alertModel.Text.ConfirmIfYouWantToCancelTheExpenseSplitRequest"
    case alertModelYouWillCancelTheRequest                                      = "alertModel.title.YouWillCancelTheRequest"
    case alertModelYourUpdateOperationsHaveBeenCarriedOut                       = "alertModel.Text.YourUpdateOperationsHaveBeenCarriedOut"
    case alertModelYouDoNotHaveACardAvailableForThisTransaction                 = "alertModel.Text.YouDoNotHaveACardAvailableForThisTransaction"
    case alertModelLimitMustBeSmall                                             = "alertModel.Text.LimitMustBeSmall"
    case alertModelUpdateAmount                                                 = "alertModel.Text.UpdateAmount"
    case alertModelPleaseCheckThePasswordYouEntered                             = "alertModel.Text.PleaseCheckThePasswordYouEntered"
    case alertModelPleaseEnterTheSamePasswords                                  = "alertModel.Text.PleaseEnterTheSamePasswords"
    case alertModelPleaseSelectASecurityQuestion                                = "alertModel.Text.PleaseSelectASecurityQuestion"
    case alertModelWhiteLabelInsufficientBalance                                = "alertModel.Text.WhiteLabelInsufficientBalance"
    case alertModelInsufficientBalance                                          = "alertModel.Text.InsufficientBalance"
    case alertModelAnErrorOccurredPleaseTryAgain                                = "alertModel.Text.AnErrorOccurredPleaseTryAgain"
    case alertModelYouCanSplitYourSpendWithAMaximumOf10People                   = "alertModel.Text.YouCanSplitYourSpendWithAMaximumOf10People"
    case alertModelYourTopUpRequestHasBeenSuccessfullyReceived                  = "alertModel.Text.YourTopUpRequestHasBeenSuccessfullyReceived"
    case alertModelYourTopUpRequestFailedPleaseTryAgainLater                    = "alertModel.Text.YourTopUpRequestFailedPleaseTryAgainLater"
    case alertModelNetworkError                                                 = "alertModel.Text.NetworkError"
    case alertModelTextPaymentRequestHasBeenSuccessfullyReceived                = "alertModel.Text.PaymentRequestHasBeenSuccessfullyReceived"
    case VerifyIdentityTitleStepOCR                                                 = "VerifyIdentity.Title.step_OCR"
    case VerifyIdentityTitleStepNFC                                                 = "VerifyIdentity.Title.step_NFC"
    case VerifyIdentityTitleStepFaceReg                                                 = "VerifyIdentity.Title.step_FACE_REG"
    
   
   
    var string: String {
      return NSLocalizedString(
            self.rawValue,
            tableName: "Localizable",
            bundle: WLResourcesBundle.bundle!,
            comment: self.rawValue
        )
    }
    
    var uppercasedString: String {
        self.string.uppercased(with: Locale(identifier: "tr_TR"))
    }
    
    func string(_ args: CVarArg...) -> String {
        String(format: self.string, arguments: args)
    }
}

extension WLTexts {
    var asText: SwiftUI.Text {
        Text(self.string).font(.body)
    }
}
